apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-minio-secret-access
spec:
  validationFailureAction: Enforce
  background: false
  rules:
    - name: restrict-minio-secret-mount
      match:
        resources:
          kinds:
            - Pod
          namespaces:
            - application
      preconditions:
        all:
          - key: "{{ request.operation }}"
            operator: NotEquals
            value: "DELETE"
          - key: "{{ request.object.spec.volumes[*].secret.secretName }}"
            operator: In
            value:
              - "minio"
          - key: "{{ request.object.spec.serviceAccountName }}"
            operator: NotEquals
            value: "data-service-sa"
      validate:
        message: "Only pods using ServiceAccount 'data-service-sa' can mount the MinIO secret."
        deny: {}
