apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: minio-access-binding
  namespace: application
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: minio-access-role
subjects:
- kind: ServiceAccount
  name: data-service-sa
  namespace: application
